# Generated by Django 3.1.4 on 2021-01-05 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='rounddata',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.course', verbose_name='Course Played'),
        ),
        migrations.AddField(
            model_name='rounddata',
            name='tees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tee', verbose_name='Course Tees'),
        ),
        migrations.AddField(
            model_name='rounddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rounds', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='practicedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='hole',
            name='tee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee_holes', to='api.tee', verbose_name='Tee'),
        ),
        migrations.AddField(
            model_name='gpshole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_holes', to='api.course', verbose_name='Course'),
        ),
    ]
