# from typing import Optional

from apps.api.models import Course

def create_app_course(
    name: str,
    course_name: str,
    address: str,
    phone: str,
    website: str,
    description: str,
    price: int,
    ext_fid: str,
    ext_cid: str,
    ext_company: str,
    ext_course: str,
    city: str,
    state: str,
    zip: str,
    streetaddress: str,
    county: str,
    lat: str,
    lon: str,
    holes: int,
    ext_holetype: str,
    ext_cat: str,
    ext_type: str,
    ext_fips: str,
    opdate: str,
    archname: str,
    fee: int,
    facility_id: str,
    status: str,
    whs_course_id: str,
    to_confirm: str,
    tg_data_is_correct: str,
    season_start: str,
    season_end: str,
) -> Course: 
    course = Course.objects.create(
    name=name,
    course_name=course_name,
    address=address,
    phone=phone,
    website=website,
    description=description,
    price=price,
    ext_fid=ext_fid,
    ext_cid=ext_cid,
    ext_company=ext_company,
    ext_course=ext_course,
    city=city,
    state=state,
    zip=zip,
    streetaddress=streetaddress,
    county=county,
    lat=lat,
    lon=lon,
    holes=holes,
    ext_holetype=ext_holetype,
    ext_cat=ext_cat,
    ext_type=ext_type,
    ext_fips=ext_fips,
    opdate=opdate,
    archname=archname,
    fee=fee,
    facility_id=facility_id,
    status=status,
    whs_course_id=whs_course_id,
    tg_data_is_correct=tg_data_is_correct,
    to_confirm=to_confirm,
    season_start=season_start,
    season_end=season_end,
    )
    return course